// Generated by https://quicktype.io

export interface Characters {
  info: Info;
  results: Character[];
}

export interface Info {
  count: number;
  pages: number;
  next: string;
  prev: null;
}

export interface Character {
  id: number;
  name: string;
  status: Status;
  species: Species;
  type: Type;
  gender: Gender;
  origin: Location;
  location: Location;
  image: string;
  episode: string[];
  url: string;
  created: string;
}

export enum Gender {
  Male = "Male",
}

export interface Location {
  name: string;
  url: string;
}

export enum Species {
  Alien = "Alien",
  Cronenberg = "Cronenberg",
  Human = "Human",
  Humanoid = "Humanoid",
}

export enum Status {
  Alive = "Alive",
  Dead = "Dead",
  Unknown = "unknown",
}

export enum Type {
  Empty = "",
  FishPerson = "Fish-Person",
  HumanWithAntennae = "Human with antennae",
  Robot = "Robot",
}

/* For petitions */
export interface ICharacterData {
  data: {
    info: Info;
    results: Character[];
  };
  isLoading: boolean;
  isError: boolean;
}
